# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fasthttpd < Formula
  desc "FastHttpd is a lightweight http server using valyala/fasthttp"
  homepage "https://github.com/fasthttpd/fasthttpd"
  version "0.4.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/fasthttpd/fasthttpd/releases/download/v0.4.1/fasthttpd_0.4.1_Darwin_arm64.tar.gz"
      sha256 "c1b87d5a924c7cec93a9b1c98f613032c27ee119cb29607c7085b9f17e9024b0"

      def install
        bin.install "fasthttpd"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/fasthttpd/fasthttpd/releases/download/v0.4.1/fasthttpd_0.4.1_Darwin_x86_64.tar.gz"
      sha256 "c33045561fc21762fadbb8b936e0885ce6e8e24acf8b6ef2fbeedfa1394c0721"

      def install
        bin.install "fasthttpd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/fasthttpd/fasthttpd/releases/download/v0.4.1/fasthttpd_0.4.1_Linux_x86_64.tar.gz"
      sha256 "e8260d4becf7b727d8590b294080949387d679d3a6a0419e7a9698fd073e6bb1"

      def install
        bin.install "fasthttpd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fasthttpd/fasthttpd/releases/download/v0.4.1/fasthttpd_0.4.1_Linux_arm64.tar.gz"
      sha256 "58815b270f7f941e4375fc63a741bfa6343a6451a444dcbbfd51e3339b2487d0"

      def install
        bin.install "fasthttpd"
      end
    end
  end

  test do
    system "#{bin}/fasthttpd -v"
  end
end
